### ISSUE TITLE
RoutingError with sub-uri

### ISSUE THREAD

**Issue by ChoiJIN** [koppen/redmine_github_hook#78]
I installed redmine with sub-uri(www.mydomain.com/redmine).

With your kind installation guide, I successfully installed Redmine Github Hook plugin which shows in Plugin pages.

But when I try POST and GET with www.mydomain.com/redmine/github_hook, both of them make routing error.

Weird thing is, I used bundle and found nothing in redmine/plugins folder. Is this normal situation?

What can I do with this problem?

---
Environment:
  Redmine version                3.2.0.stable.14983
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_github_hook            2.2.0

---
ActionController::RoutingError (No route matches [POST] "/redmine/github_hook"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
  puma (2.15.3) lib/puma/configuration.rb:79:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

ActionController::RoutingError (No route matches [GET] "/redmine/github_hook"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
  puma (2.15.3) lib/puma/configuration.rb:79:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

**Comment by koppen** [comment]
Thanks for reporting this! I didn't even know Redmine supported serving itself from a sub URI.

Looking at http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI there are quite a few ways you could have achieved this; which method have you used to configure Redmine to run in this way?

**Comment by ChoiJIN** [comment]
I saw that page, and used "Using Unicorn+Nginx" configuration.

**Comment by YounesN** [comment]
Have the same issue. Any update on this?

**Comment by koppen** [comment]
Looking at http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI there are quite a few ways you could have achieved this; which method have you used to configure Redmine to run in this way?
