### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by texnoid** [koppen/redmine_github_hook#83]
Hi.

Environment:
  Redmine version                2.6.10.stable
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.22.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_github_hook            2.2.0
  redmine_watcher_groups         0.0.1

 ```
NoMethodError (undefined method `downcase' for 252:Fixnum):
 plugins/redmine_github_hook/app/services/github_hook/updater.rb:71:in `find_project'
  plugins/redmine_github_hook/app/services/github_hook/updater.rb:81:in `find_repositories'
  plugins/redmine_github_hook/app/services/github_hook/updater.rb:13:in `call'
  plugins/redmine_github_hook/app/controllers/github_hook_controller.rb:42:in `update_repository'
  plugins/redmine_github_hook/app/controllers/github_hook_controller.rb:8:in `index'
  actionpack (3.2.22.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.22.2) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:458:in `_run__1967744784485400790__process_action__3822553068097814306__callbacks'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.22.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.22.2) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.22.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.22.2) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.22.2) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.22.2) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.22.2) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.22.2) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.22.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `_run__1686921822559580354__call__842289762549179126__callbacks'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22.2) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22.2) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.6.1) lib/rack/cache/context.rb:140:in `forward'
  rack-cache (1.6.1) lib/rack/cache/context.rb:147:in `pass'
  rack-cache (1.6.1) lib/rack/cache/context.rb:159:in `invalidate'
  rack-cache (1.6.1) lib/rack/cache/context.rb:74:in `call!'
  rack-cache (1.6.1) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.22.2) lib/rails/engine.rb:484:in `call'
  railties (3.2.22.2) lib/rails/application.rb:231:in `call'
  railties (3.2.22.2) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.50) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.50) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.50) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.50) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

```
Started GET "/github_hook" for 10.2.151.0 at 2016-03-18 12:21:41 +0000
Processing by GithubHookController#welcome as HTML
  Current user: demo (id=255)
  Rendered plugins/redmine_github_hook/app/views/github_hook/welcome.html.erb within layouts/base (0.4ms)
Completed 200 OK in 35.7ms (Views: 27.4ms | ActiveRecord: 5.3ms)

```

**Comment by koppen** [comment]
Thanks for reporting this, I've got a fix incoming.

I'm curious; what request results in `project_id` being numeric like this? Is this from GitHub?
