### ISSUE TITLE
ActiveRecord::RecordNotUnique when git has hash-collision(?)

### ISSUE THREAD

**Issue by yukihane** [koppen/redmine_github_hook#85]
```
ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '10-ef898a9dcfd82777da9eb9eb0bb3c9ece4ab1e1d' for key 'changesets_repos_rev': 
INSERT INTO `changesets` (`repository_id`, `revision`, `scmid`, `committer`, `commit_date`, `committed_on`, `comments`) VALUES (10, 'ef898a9dcfd82777da9eb9eb0bb3c9ece4ab1e1d', [snip]):
  app/models/repository/git.rb:218:in `save_revision'
  app/models/repository/git.rb:207:in `block (2 levels) in save_revisions'
  app/models/repository/git.rb:204:in `block in save_revisions'
  app/models/repository/git.rb:203:in `each'
  app/models/repository/git.rb:203:in `save_revisions'
  app/models/repository/git.rb:153:in `fetch_changesets'
  plugins/redmine_github_hook/app/services/github_hook/updater.rb:23:in `block in call'
  plugins/redmine_github_hook/app/services/github_hook/updater.rb:15:in `each'
  plugins/redmine_github_hook/app/services/github_hook/updater.rb:15:in `call'
  plugins/redmine_github_hook/app/controllers/github_hook_controller.rb:42:in `update_repository'
  plugins/redmine_github_hook/app/controllers/github_hook_controller.rb:8:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by yukihane** [comment]
Very large repository causes this problem.
After trying multiple execution, all changesets is inserted.
