### ISSUE TITLE
Error: undefined method `skip_before_filter' for GithubHookController:Class

### ISSUE THREAD

**Issue by petarjov** [koppen/redmine_github_hook#87]
Hi, 
I followed the instructions for setting up redmine github hook for my Redmine installation.  When restarting Redmine, I am getting an exception below:
My Redmine version is: 
--------------------------------------
Environment:
  Redmine version                3.4.2.devel
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  5.1.2
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  no plugin installed
--------------------------------------
Exception:

/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redmine_github_hook-2.2.0/app/controllers/github_hook_controller.rb:4:in `<class:GithubHookController>': undefined method `skip_before_filter' for GithubHoo         kController:Class (NoMethodError)
Did you mean?  skip_before_action
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/redmine_github_hook-2.2.0/app/controllers/github_hook_controller.rb:3:in `<top (required)>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:379:in `block in require_or_load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `block in load_interlock'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `load_interlock'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:357:in `require_or_load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:335:in `depend_on'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:251:in `require_dependency'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:475:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:475:in `block in eager_load!'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:473:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:473:in `eager_load!'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:354:in `eager_load!'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/application/finisher.rb:67:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
        from /root/redmine/config/environment.rb:14:in `<top (required)>'
        from config.ru:3:in `require'
        from config.ru:3:in `block in <main>'

**Comment by koppen** [comment]
Much appreciated, thanks for reporting this.

By the looks of things it seems that Redmine Github Hook isn't compatible with newer versions of Redmine. I don't think it has been tested on anything newer than the 2.x line, and especially the newer, Rails 5 based versions are likely not going to work.

The fix should be fairly simple, at least if the above error is the only problem; replacing `skip_before_filter` with `skip_before_action` should make things work, albeit in a non-backwards-compatible manner.

I'll see if I can find some time for this, but I promise no timeframe, so pull requests beating me to it are welcome.

**Comment by roman-yagodin** [comment]
The plugin of version 2.2 (installed from gem) works fine with my Redmine v3.4.2 install on Rails v4.2.8, Ruby v2.3. 

According to http://www.redmine.org/projects/redmine/wiki/RedmineInstall, Redmine 3.4 should use Rails 4.2.

**Comment by koppen** [comment]
Cool, thanks for the details, @roman-yagodin .

@petarjov, it looks like you are on the pre-release line (3.4.2.devel), which supposedly has been upgraded to use Rails 5.1 in preparation for Redmine 4.x.

It seems you should be fine if you use the released 3.4.2 version of Redmine.

**Comment by koppen** [comment]
Closing due to lack of activity; presuming the issue has been fixed.
